name: Deploy

on:
  push:
    branches:
      - "*"
      - "!skipci*"

concurrency:
  group: ${{ github.ref_name }}-group

permissions:
  id-token: write
  contents: read
  actions: read

env:
  branch_name: ${{ github.ref_name }}
  SLS_DEPRECATION_DISABLE: "*" # Turn off deprecation warnings in the pipeline
  AWS_DEFAULT_REGION: us-east-1
jobs:
  initialize:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Validate stage name
        run: |
          if [[ ! $branch_name =~ ^[a-z][a-z0-9-]*$ ]]; then
              echo "ERROR:  Your branch name, $branch_name, is not a valid Serverless Framework stage name." && exit 1
          fi
  unit-test:
    runs-on: ubuntu-latest
    needs: initialize
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v2
      - name: read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: unit-test-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: run unit tests
        run: ./scripts/unit_test.sh
      - name: publish test coverage to code climate
        if: env.CC_TEST_REPORTER_ID != ''
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/services/ui-src/coverage/lcov.info:lcov
      - name: Store unit test reults
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_results
          path: ${{github.workspace}}/services/ui-src/coverage/lcov.info
  build-images:
    runs-on: ubuntu-latest
    needs: initialize
    environment:
      name: ${{ github.ref_name }}
    outputs:
      ecr_repository_uri: ${{ steps.build.outputs.ecr_repository_uri }}
      image_tag: ${{ steps.build.outputs.image_tag }}
      frontend_image: ${{ steps.build.outputs.frontend_image }}
    steps:
      - uses: actions/checkout@v2
      - name: read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: build-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: deploy support
        if: env.branch_name == 'master'
        run: |
          ./scripts/deploy_support.sh $branch_name
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: build
        id: build
        run: |
          yarn install --frozen-lockfile
          pushd services
          export ecr_repository_uri=`./output.sh .ecr ECRRepositoryUri master`
          echo "ecr_repository_uri=$ecr_repository_uri" >> $GITHUB_ENV
          echo "::set-output name=ecr_repository_uri::$ecr_repository_uri"
          echo "::set-output name=image_tag::$GITHUB_SHA"
          echo "::set-output name=frontend_image::$ecr_repository_uri:$GITHUB_SHA"
          popd
          cd services/ui-src
          docker build . -t $ecr_repository_uri:$GITHUB_SHA
          account_id=`aws sts get-caller-identity --query "Account" --output text --region us-east-1`
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $account_id.dkr.ecr.us-east-1.amazonaws.com
          docker push $ecr_repository_uri:$GITHUB_SHA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  scan-images:
    runs-on: ubuntu-latest
    needs: build-images
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Scan Docker image
        id: docker-scan
        uses: alexjurkiewicz/ecr-scan-image@v1.7.0
        with:
          repository: frontend
          tag: ${{ needs.build-images.outputs.image_tag }}
          fail_threshold: high
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-images
      - scan-images
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.application_endpoint }}
    steps:
      - uses: actions/checkout@v2
      - name: read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: deploy-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: deploy
        id: deploy
        run: |
          export frontend_image=${{ needs.build-images.outputs.frontend_image }}
          ./scripts/deploy.sh $branch_name
          pushd services
          export APPLICATION_ENDPOINT=`./output.sh ui ApplicationEndpointUrl $branch_name`
          echo "::set-output name=application_endpoint::$APPLICATION_ENDPOINT"
          echo "Application endpoint: $APPLICATION_ENDPOINT"
          popd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: env.SLACK_WEBHOOK_URL != '' && contains(fromJson('["master", "val", "production"]'), env.branch_name) && failure ()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: Destroy Alerts
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_COLOR: ${{job.status}}
          SLACK_FOOTER: ""
          MSG_MINIMAL: actions url,commit,ref
  cypress-test:
    name: Cypress Tests
    needs: deploy
    if: ${{ github.ref != 'refs/heads/prod' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [test.spec.js, test2.spec.js]
    steps:
      - uses: actions/checkout@v1
      - name: read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: deploy-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: Endpoint
        run: |
          pushd services
          export APPLICATION_ENDPOINT=`./output.sh ui ApplicationEndpointUrl $branch_name`
          echo "APPLICATION_ENDPOINT=$APPLICATION_ENDPOINT" >> $GITHUB_ENV
          echo "Application endpoint: $APPLICATION_ENDPOINT"
          popd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: tests/cypress
          spec: integration/${{ matrix.containers }}
          browser: chrome
          headless: true
          config: baseUrl=${{ env.APPLICATION_ENDPOINT }}
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots/
  a11y-tests:
    name: A11y Tests
    needs: deploy
    if: ${{ github.ref != 'refs/heads/prod' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [homePage]
    steps:
      - uses: actions/checkout@v1
      - name: read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: deploy-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: set path
        run: |
          echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
      - name: Endpoint
        run: |
          pushd services
          export APPLICATION_ENDPOINT=`./output.sh ui ApplicationEndpointUrl $branch_name`
          echo "APPLICATION_ENDPOINT=$APPLICATION_ENDPOINT" >> $GITHUB_ENV
          echo "Application endpoint: $APPLICATION_ENDPOINT"
          popd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Check Project A11y
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: tests/cypress
          spec: integration/a11y/${{ matrix.containers }}.spec.js
          browser: chrome
          headless: true
          config: baseUrl=${{ env.APPLICATION_ENDPOINT }}
